services:
  postgres:
    build: .
    image: ankane/pgvector:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: system
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mockinterview
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
