#!/bin/bash
# Oracle Cloud deployment script with Vault integration
# This script sets up the application on an OCI compute instance with Vault secrets

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${GREEN}"
echo "╔════════════════════════════════════════╗"
echo "║  MockInterview Oracle Cloud Deployer  ║"
echo "║     With Vault Secret Management      ║"
echo "╚════════════════════════════════════════╝"
echo -e "${NC}"

# Check if running as root
if [ "$EUID" -eq 0 ]; then 
    echo -e "${YELLOW}⚠️  Please don't run as root. Run as oracle user instead.${NC}"
    exit 1
fi

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# 1. Check prerequisites
echo -e "${BLUE}[1/8] Checking prerequisites...${NC}"

if ! command_exists docker; then
    echo -e "${RED}❌ Docker is not installed${NC}"
    exit 1
fi

if ! command_exists docker-compose; then
    echo -e "${RED}❌ Docker Compose is not installed${NC}"
    exit 1
fi

if ! command_exists oci; then
    echo -e "${YELLOW}⚠️  OCI CLI not found. Installing...${NC}"
    bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" -- --accept-all-defaults
    export PATH=$PATH:~/bin
fi

echo -e "${GREEN}✅ Prerequisites check complete${NC}"

# 2. Verify instance principal authentication
echo -e "${BLUE}[2/8] Verifying instance principal authentication...${NC}"

if curl -s -f -m 5 http://169.254.169.254/opc/v2/instance/ -H "Authorization: Bearer Oracle" > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Instance principal authentication available${NC}"
    USE_INSTANCE_PRINCIPAL=true
else
    echo -e "${YELLOW}⚠️  Instance principal not available. Will use OCI config file.${NC}"
    USE_INSTANCE_PRINCIPAL=false
    
    if [ ! -f ~/.oci/config ]; then
        echo -e "${YELLOW}⚠️  OCI config not found. Setting up...${NC}"
        oci setup config
    fi
fi

# 3. Load configuration
echo -e "${BLUE}[3/8] Loading configuration...${NC}"

if [ -f .env.vault ]; then
    source .env.vault
    echo -e "${GREEN}✅ Loaded .env.vault${NC}"
else
    echo -e "${YELLOW}⚠️  .env.vault not found${NC}"
    read -p "Do you want to use Oracle Vault for secrets? (y/n): " use_vault
    
    if [ "$use_vault" == "y" ]; then
        echo -e "${YELLOW}Creating .env.vault from template...${NC}"
        cp .env.vault.example .env.vault
        echo -e "${YELLOW}Please edit .env.vault with your configuration and run this script again.${NC}"
        exit 0
    else
        echo -e "${YELLOW}Will use traditional .env file${NC}"
        USE_ORACLE_VAULT=false
    fi
fi

# 4. Test Vault connectivity (if enabled)
if [ "${USE_ORACLE_VAULT}" == "true" ]; then
    echo -e "${BLUE}[4/8] Testing Vault connectivity...${NC}"
    
    # Try to list secrets
    if oci vault secret list \
        --compartment-id "$OCI_COMPARTMENT_ID" \
        --vault-id "$OCI_VAULT_ID" \
        --limit 1 > /dev/null 2>&1; then
        echo -e "${GREEN}✅ Successfully connected to Oracle Vault${NC}"
        
        # List available secrets
        echo -e "${YELLOW}Available secrets:${NC}"
        oci vault secret list \
            --compartment-id "$OCI_COMPARTMENT_ID" \
            --vault-id "$OCI_VAULT_ID" \
            --query 'data[*].[\"secret-name\",\"lifecycle-state\"]' \
            --output table
    else
        echo -e "${RED}❌ Failed to connect to Oracle Vault${NC}"
        echo "Please check:"
        echo "  1. Your OCI_VAULT_ID and OCI_COMPARTMENT_ID are correct"
        echo "  2. IAM policies allow reading secrets"
        echo "  3. Dynamic group includes this instance"
        exit 1
    fi
else
    echo -e "${BLUE}[4/8] Skipping Vault connectivity test (Vault disabled)${NC}"
fi

# 5. Prepare environment file
echo -e "${BLUE}[5/8] Preparing environment configuration...${NC}"

if [ "${USE_ORACLE_VAULT}" == "true" ]; then
    # Create minimal .env for non-secret configs
    cat > .env <<EOF
# Generated by deploy script - $(date)
# Secrets are fetched from Oracle Vault

# Basic configuration
NODE_ENV=production
PORT=8080
BASE_URL=http://localhost

# Database configuration (non-secret)
POSTGRES_USER=${POSTGRES_USER:-system}
POSTGRES_DB=${POSTGRES_DB:-mockinterview}
POSTGRES_HOST=postgres
POSTGRES_PORT=5432

# Redis configuration
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_URL=redis://redis:6379

# Oracle Vault configuration
USE_ORACLE_VAULT=true
OCI_USE_INSTANCE_PRINCIPAL=${USE_INSTANCE_PRINCIPAL}
OCI_REGION=${OCI_REGION}
OCI_COMPARTMENT_ID=${OCI_COMPARTMENT_ID}
OCI_VAULT_ID=${OCI_VAULT_ID}

# Secret OCIDs
SECRET_POSTGRES_PASSWORD_OCID=${SECRET_POSTGRES_PASSWORD_OCID}
SECRET_GOOGLE_API_KEY_OCID=${SECRET_GOOGLE_API_KEY_OCID}
SECRET_FIREBASE_PROJECT_ID_OCID=${SECRET_FIREBASE_PROJECT_ID_OCID}
SECRET_FIREBASE_CLIENT_EMAIL_OCID=${SECRET_FIREBASE_CLIENT_EMAIL_OCID}
SECRET_FIREBASE_PRIVATE_KEY_OCID=${SECRET_FIREBASE_PRIVATE_KEY_OCID}

# Authentication
AUTH_ENABLED=${AUTH_ENABLED:-true}
EOF
    
    echo -e "${GREEN}✅ Environment configured with Vault integration${NC}"
else
    if [ ! -f .env ]; then
        echo -e "${YELLOW}⚠️  .env file not found. Creating from example...${NC}"
        cp .env.example .env
        echo -e "${YELLOW}Please edit .env with your configuration and run this script again.${NC}"
        exit 0
    fi
    echo -e "${GREEN}✅ Using existing .env file${NC}"
fi

# 6. Build and pull images
echo -e "${BLUE}[6/8] Building and pulling Docker images...${NC}"

if [ "${USE_ORACLE_VAULT}" == "true" ]; then
    docker-compose -f docker-compose.vault.yaml build
    docker-compose -f docker-compose.vault.yaml pull postgres redis
else
    docker-compose -f docker-compose.prod.yaml build
    docker-compose -f docker-compose.prod.yaml pull postgres redis
fi

echo -e "${GREEN}✅ Docker images ready${NC}"

# 7. Stop existing containers
echo -e "${BLUE}[7/8] Stopping existing containers...${NC}"

if [ "${USE_ORACLE_VAULT}" == "true" ]; then
    docker-compose -f docker-compose.vault.yaml down || true
else
    docker-compose -f docker-compose.prod.yaml down || true
fi

echo -e "${GREEN}✅ Existing containers stopped${NC}"

# 8. Start services
echo -e "${BLUE}[8/8] Starting services...${NC}"

if [ "${USE_ORACLE_VAULT}" == "true" ]; then
    docker-compose -f docker-compose.vault.yaml up -d
    COMPOSE_FILE="docker-compose.vault.yaml"
else
    docker-compose -f docker-compose.prod.yaml up -d
    COMPOSE_FILE="docker-compose.prod.yaml"
fi

# Wait for services to be healthy
echo -e "${YELLOW}Waiting for services to be healthy...${NC}"
sleep 5

# Check service status
echo ""
echo -e "${GREEN}Service Status:${NC}"
docker-compose -f "$COMPOSE_FILE" ps

# Check logs for any startup errors
echo ""
echo -e "${YELLOW}Recent logs (checking for errors):${NC}"
docker-compose -f "$COMPOSE_FILE" logs --tail=20 backend

# Test health endpoint
echo ""
echo -e "${BLUE}Testing application health...${NC}"
sleep 5

if curl -f -s http://localhost:8080/health > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Application is healthy and responding${NC}"
else
    echo -e "${YELLOW}⚠️  Health check failed. Check logs with:${NC}"
    echo "    docker-compose -f $COMPOSE_FILE logs -f backend"
fi

# Summary
echo ""
echo -e "${GREEN}"
echo "╔════════════════════════════════════════╗"
echo "║     Deployment Complete! 🎉            ║"
echo "╚════════════════════════════════════════╝"
echo -e "${NC}"

echo "Configuration:"
echo "  • Vault Enabled: ${USE_ORACLE_VAULT:-false}"
echo "  • Instance Principal: ${USE_INSTANCE_PRINCIPAL}"
echo "  • Compose File: $COMPOSE_FILE"
echo ""
echo "Application URLs:"
echo "  • API: http://localhost:8080"
echo "  • Health: http://localhost:8080/health"
echo ""
echo "Useful commands:"
echo "  • View logs:       docker-compose -f $COMPOSE_FILE logs -f"
echo "  • Restart:         docker-compose -f $COMPOSE_FILE restart"
echo "  • Stop:            docker-compose -f $COMPOSE_FILE down"
echo "  • View status:     docker-compose -f $COMPOSE_FILE ps"
echo ""

if [ "${USE_ORACLE_VAULT}" == "true" ]; then
    echo "Vault Management:"
    echo "  • List secrets:    oci vault secret list --compartment-id $OCI_COMPARTMENT_ID"
    echo "  • Rotate secret:   ./scripts/create-vault-secrets.sh"
    echo ""
fi

echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Configure your firewall/security list to allow port 8080"
echo "  2. Set up SSL/TLS with a reverse proxy (nginx/caddy)"
echo "  3. Configure monitoring and backups"
echo "  4. Test all API endpoints"
echo ""
echo -e "${GREEN}Happy coding! 🚀${NC}"
